version: 2

sources:
# Sources listed below should closely resemble the names of your Fivetran connectors. Names are at your descretion. Schema's will mirror your destination schemas.

  - name: animal_crossing_animals # this can be whatever I want
    schema: SQL_SERVER_RDS_ANIMAL_CROSSING # Connector and first schema name for connector with MULTIPLE SCHEMAS
    tables:
      - name: fish
      - name: insects


# For additional configuration, visit https://docs.getdbt.com/reference/source-properties
        

